// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7JHZeRlNe88MKj_N6XuCWL8lI3AJSGxw',
    appId: '1:865270517893:web:ae1216151fe33614ca99ec',
    messagingSenderId: '865270517893',
    projectId: 'reflipstore',
    authDomain: 'reflipstore.firebaseapp.com',
    storageBucket: 'reflipstore.firebasestorage.app',
    measurementId: 'G-3SWDQECQ81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZyEXUjLs8H8YwVPXIYyRac53rjbcisIE',
    appId: '1:865270517893:android:b1f15b44ef865021ca99ec',
    messagingSenderId: '865270517893',
    projectId: 'reflipstore',
    storageBucket: 'reflipstore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMVaQvUSGg9f-7FfaU_wPGX1_dHReU3Bk',
    appId: '1:865270517893:ios:a02b1ba715df4215ca99ec',
    messagingSenderId: '865270517893',
    projectId: 'reflipstore',
    storageBucket: 'reflipstore.firebasestorage.app',
    iosBundleId: 'com.example.reflipStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMVaQvUSGg9f-7FfaU_wPGX1_dHReU3Bk',
    appId: '1:865270517893:ios:a02b1ba715df4215ca99ec',
    messagingSenderId: '865270517893',
    projectId: 'reflipstore',
    storageBucket: 'reflipstore.firebasestorage.app',
    iosBundleId: 'com.example.reflipStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7JHZeRlNe88MKj_N6XuCWL8lI3AJSGxw',
    appId: '1:865270517893:web:c18d9129c26d5b85ca99ec',
    messagingSenderId: '865270517893',
    projectId: 'reflipstore',
    authDomain: 'reflipstore.firebaseapp.com',
    storageBucket: 'reflipstore.firebasestorage.app',
    measurementId: 'G-QH7PJEK2HR',
  );
}
